# Generated by Django 5.2.14 on 2026-05-11 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(choices=[('team', 'Team'), ('public', 'Public')], default='team', max_length=20)),
                ('public_token', models.CharField(blank=True, default='', max_length=64)),
                ('refresh_interval', models.PositiveIntegerField(default=60)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=128)),
                ('aggregation', models.CharField(max_length=64)),
                ('group_by', models.CharField(blank=True, default='', max_length=128)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('time_range', models.CharField(default='7d', max_length=32)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar'), ('doughnut', 'Doughnut'), ('area', 'Area'), ('kpi', 'KPI'), ('table', 'Table')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('position', models.JSONField(default=dict)),
                ('query_config', models.JSONField(blank=True, default=dict)),
                ('chart_config', models.JSONField(blank=True, default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboard')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
