# Generated by Django 5.2.14 on 2026-05-11 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('metric', models.CharField(max_length=128)),
                ('operator', models.CharField(choices=[('>', '>'), ('<', '<'), ('==', '=='), ('>=', '>='), ('<=', '<=')], max_length=4)),
                ('threshold', models.FloatField()),
                ('duration_seconds', models.PositiveIntegerField(default=300)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Triggered', 'Triggered'), ('Resolved', 'Resolved'), ('Muted', 'Muted')], default='Active', max_length=20)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.FloatField()),
                ('message', models.TextField()),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alertrule')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('webhook', 'Webhook')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('response_body', models.TextField(blank=True, default='')),
                ('alert_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.alerthistory')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.notificationchannel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'status'], name='alerts_aler_organiz_6aba83_idx'),
        ),
    ]
